### ISSUE TITLE
Could you please provide the code for getting the wave format for the given .CSV data for a time period.

### ISSUE THREAD

**Issue by vmadhavan15** [Louisli0515/Stock-market-#1]
Could you please provide the code for getting the wave format for the given .CSV data for a time period say for example of 1 year data.

**Comment by Louisli0515** [comment]
What do you mean by getting the wave format? Did you mean how to determine whether it is in wave 1, wave 2 or wave 3... or you want to have the closing prices of a stock of 1 year?

**Comment by vmadhavan15** [comment]
i mean to have the historical data wave output, if I give the historical data as input and that will give me the wave format output.
